=== passanthamdy/XML/Day2/emp.dtd
<!ELEMENT empContact (info+)>
<!ELEMENT info (name, phones,addresses,email)>
<!ELEMENT phones (phone+)>
<!ATTLIST phone type CDATA #REQUIRED>
<!ELEMENT phone (#PCDATA)>

<!ELEMENT addresses (address1,address2)>
<!ELEMENT address1 (street , buildingno, region,city , country)>
<!ELEMENT address2 (street , buildingno, region,city , country)>
<!ELEMENT street (#PCDATA)>
<!ELEMENT buildingno (#PCDATA)>
<!ELEMENT region (#PCDATA)>
<!ELEMENT city (#PCDATA)>
<!ELEMENT country (#PCDATA)>

<!ELEMENT name (#PCDATA)>
<!ELEMENT email (#PCDATA)  >
<!ELEMENT body (#PCDATA)>

=== passanthamdy/XML/Day2/Employee.xml
<?xml version="1.0"?>
<!DOCTYPE empContact SYSTEM "emp.dtd">
<?xml-stylesheet type="text/css" href="emp.css"?>

<empContact>
	<info>
		<name>Passant</name>
		<phones>
			<phone type="mobile">019012589215</phone>
			<phone type="home">78922313</phone>
		</phones>
		<addresses>
			<address1>
				<street>Street1</street>
				<buildingno>99</buildingno>
				<region>Alex</region>
				<city>Alexandria</city>
				<country>Egypt</country>
			</address1>
			<address2>
				<street>street2</street>
				<buildingno>22</buildingno>
				<region>Alex</region>
				<city>Alexandria</city>
				<country>Egypt</country>
			</address2>
		</addresses>
		<email>Passant@gmail.com</email>

	</info>
	<info>
		<name>Youmna</name>
		<phones>
			<phone type="mobile">019012589215</phone>
			<phone type="home">78922313</phone>
		</phones>
		<addresses>
			<address1>
				<street>Street1</street>
				<buildingno>99</buildingno>
				<region>Alex</region>
				<city>Alexandria</city>
				<country>Egypt</country>
			</address1>
			<address2>
				<street>street2</street>
				<buildingno>22</buildingno>
				<region>Alex</region>
				<city>Alexandria</city>
				<country>Egypt</country>
			</address2>
		</addresses>
		<email>youmna@gmail.com</email>

	</info>
</empContact>
